# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be93a6ec98060428041fd0799ea8ac0832fa595ae44d423e25a9c4e0ebc228e21d73c1fa400fb0b5d67b2bfebe545731eeeea3e0d2197051e131f54ad1b9b36f

test:
  secret_key_base: 07f757cfbf055d06b423c33ebb26690217d73c35e78166c6535f917278ff35217729210267c63deb82102e4c5c37429739fd5f67d6beb6b9f2d7efd8735ad73f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
